site_name: 数据库课程实验资源平台
site_description: 数字化转型背景下数据库课程实验教学资源的共建共享
site_url: https://gitee.com/kidzying/dbwiki
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal

nav:
  - 首页: index.md
  - 错误SQL点评: 
    - 语法错误: 1_sql_pitfalls/syntax_groupby错误_teacher.md
  - 企业案例: 
    - 电商优化: 2_enterprise_cases/ecommerce_查询优化_teacher.md
  - 避坑指南: 
    - 事务处理: 3_avoidance_guides/transaction_死锁避免_teacher.md
  - 实验示范: 
    - 基础查询: 4_excellent_labs/lab1_基础查询_student.md
    - 触发器与存储过程：教材案例的MySQL实现: 4_excellent_labs/触发器与存储过程教材案例MySQL实现.md
  - 课设案例: 
    - 图书系统: 5_course_designs/library_管理系统_student.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
